package constants

import "skycrypt/src/models"

var PLAYER_STATS = map[string]models.StatsInfo{
	"health":                {"base": 100},
	"defense":               {"base": 0},
	"strength":              {"base": 0},
	"speed":                 {"base": 100},
	"critical_chance":       {"base": 30},
	"critical_damage":       {"base": 50},
	"intelligence":          {"base": 0},
	"bonus_attack_speed":    {"base": 0},
	"sea_creature_chance":   {"base": 20},
	"magic_find":            {"base": 0},
	"pet_luck":              {"base": 0},
	"true_defense":          {"base": 0},
	"ferocity":              {"base": 0},
	"ability_damage":        {"base": 0},
	"mining_speed":          {"base": 0},
	"mining_fortune":        {"base": 0},
	"farming_fortune":       {"base": 0},
	"foraging_fortune":      {"base": 0},
	"pristine":              {"base": 0},
	"fishing_speed":         {"base": 0},
	"health_regen":          {"base": 100},
	"vitality":              {"base": 100},
	"mending":               {"base": 100},
	"combat_wisdom":         {"base": 0},
	"mining_wisdom":         {"base": 0},
	"farming_wisdom":        {"base": 0},
	"foraging_wisdom":       {"base": 0},
	"fishing_wisdom":        {"base": 0},
	"enchanting_wisdom":     {"base": 0},
	"alchemy_wisdom":        {"base": 0},
	"carpentry_wisdom":      {"base": 0},
	"runecrafting_wisdom":   {"base": 0},
	"social_wisdom":         {"base": 0},
	"mining_spread":         {"base": 0},
	"gemstone_spread":       {"base": 0},
	"ore_fortune":           {"base": 0},
	"block_fortune":         {"base": 0},
	"dwarven_metal_fortune": {"base": 0},
	"gemstone_fortune":      {"base": 0},
	"wheat_fortune":         {"base": 0},
	"carrot_fortune":        {"base": 0},
	"potato_fortune":        {"base": 0},
	"pumpkin_fortune":       {"base": 0},
	"melon_fortune":         {"base": 0},
	"mushroom_fortune":      {"base": 0},
	"cactus_fortune":        {"base": 0},
	"sugar_cane_fortune":    {"base": 0},
	"nether_wart_fortune":   {"base": 0},
	"cocoa_beans_fortune":   {"base": 0},
	"double_hook_chance":    {"base": 0},
	"trophy_fish_chance":    {"base": 0},
	"heat_resistance":       {"base": 0},
	"fear":                  {"base": 0},
}
