name: Website

on:
  push:
    paths: ["src/**", "Dockerfile", ".github/workflows/website.yml"]
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Go Build
    runs-on: ubuntu-latest
    if: |
      (github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/dev')
      && github.repository_owner == 'SkyCryptWebsite'
      && github.event_name != 'pull_request'

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Clone NotEnoughUpdates-REPO
        uses: actions/checkout@v4
        with:
          repository: NotEnoughUpdates/NotEnoughUpdates-REPO
          path: NotEnoughUpdates-REPO/
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Go Setup
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Install packages
        run: go mod download

      - name: Build
        run: go build -v ./...

  package:
    name: Package into Container
    runs-on: ubuntu-latest
    needs: [build]
    if: |
      (github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/dev')
      && github.repository_owner == 'SkyCryptWebsite'
      && github.event_name != 'pull_request'

    permissions:
      packages: write
      contents: read

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
